require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBluetoothLe', :path => '../../../node_modules/@capacitor-community/bluetooth-le'
  pod 'CapacitorMlkitBarcodeScanning', :path => '../../../node_modules/@capacitor-mlkit/barcode-scanning'
  pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../../node_modules/@capacitor/app-launcher'
  pod 'CapacitorClipboard', :path => '../../../node_modules/@capacitor/clipboard'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../node_modules/@capacitor/keyboard'
  pod 'CapacitorPushNotifications', :path => '../../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../../node_modules/@capacitor/share'
  pod 'CapgoCapacitorNativeBiometric', :path => '../../../node_modules/@capgo/capacitor-native-biometric'
  pod 'CapgoNativeAudio', :path => '../../../node_modules/@capgo/native-audio'
  pod 'MauricewegnerCapacitorNavigationBar', :path => '../../../node_modules/@mauricewegner/capacitor-navigation-bar'
  pod 'SinaKhMtwCapacitorStatusBar', :path => '../../../node_modules/@sina_kh/mtw-capacitor-status-bar'
  pod 'CapacitorNativeSettings', :path => '../../../node_modules/capacitor-native-settings'
  pod 'CapacitorPluginSafeArea', :path => '../../../node_modules/capacitor-plugin-safe-area'
  pod 'CapacitorSecureStoragePlugin', :path => '../../../node_modules/capacitor-secure-storage-plugin'
  pod 'MtwCapacitorUsbHid', :path => '../../../node_modules/mtw-capacitor-usb-hid'
  pod 'NativeBottomSheet', :path => '../../plugins/native-bottom-sheet'
  pod 'NativeDialog', :path => '../../plugins/native-dialog'
  pod 'SinaKhMtwCapacitorSplashScreen', :path => '../../../node_modules/@sina_kh/mtw-capacitor-splash-screen'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'MyTonWallet' do
  capacitor_pods
  # Add your Pods here
  pod 'FloatingPanel', :git => 'https://github.com/mytonwalletorg/FloatingPanel', :commit => 'f58a8b94008540e680faba61867debf8b3cec682'
  pod 'FirebaseMessaging'
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
