package org.mytonwallet.app_air.uicomponents

object AnimationConstants {
    private const val DURATION_MULTIPLIER = 1L
    const val SUPER_QUICK_ANIMATION = 100L * DURATION_MULTIPLIER
    const val VERY_VERY_QUICK_ANIMATION = 150L * DURATION_MULTIPLIER
    const val VERY_QUICK_ANIMATION = 250L * DURATION_MULTIPLIER
    const val QUICK_ANIMATION = 300L * DURATION_MULTIPLIER
    const val SLOW_ANIMATION = 500L * DURATION_MULTIPLIER
    const val VERY_SLOW_ANIMATION = 1000L * DURATION_MULTIPLIER
    const val VERY_VERY_SLOW_ANIMATION = 2000L * DURATION_MULTIPLIER

    const val NAV_POP = 200L * DURATION_MULTIPLIER
    const val NAV_PRESENT = 400L * DURATION_MULTIPLIER
    const val NAV_DISMISS = 200L * DURATION_MULTIPLIER

    const val MENU_PRESENT = 500L * DURATION_MULTIPLIER
    const val MENU_DISMISS = 200L * DURATION_MULTIPLIER

    const val DIALOG_PRESENT = 500L * DURATION_MULTIPLIER
    const val DIALOG_DISMISS = 200L * DURATION_MULTIPLIER
}
